# Generated by Django 2.0.2 on 2018-05-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180515_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Article'),
        ),
    ]
