# Generated by Django 2.0.2 on 2018-05-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180515_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='blog.Article'),
        ),
    ]
