# Generated by Django 2.0.2 on 2018-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180514_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='No text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='New Tittle', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
