# Generated by Django 2.0.2 on 2018-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180515_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='somethin.com'),
            preserve_default=False,
        ),
    ]
