# Generated by Django 2.0.2 on 2018-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180515_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='number',
        ),
        migrations.AddField(
            model_name='vote',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
