# Generated by Django 2.0.2 on 2018-05-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180515_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pubdate'], 'permissions': (('can_change_status', 'Can see and change articles'),)},
        ),
    ]
